// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlAeNXbtWYKAUCffIZzwlJI01JeUC0KGY',
    appId: '1:22700401021:web:5f21836ad205c86e3cec14',
    messagingSenderId: '22700401021',
    projectId: 'oneshot-1107f',
    authDomain: 'oneshot-1107f.firebaseapp.com',
    storageBucket: 'oneshot-1107f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2DGQRqAri9KvXLg7pb3BeMyeDyM-Bs44',
    appId: '1:22700401021:android:cea535357c95faa33cec14',
    messagingSenderId: '22700401021',
    projectId: 'oneshot-1107f',
    storageBucket: 'oneshot-1107f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZiTuUaxrzhe3iWtT9zXGomvtGLLKn8c',
    appId: '1:22700401021:ios:eb85b7d432d9c33a3cec14',
    messagingSenderId: '22700401021',
    projectId: 'oneshot-1107f',
    storageBucket: 'oneshot-1107f.firebasestorage.app',
    iosBundleId: 'com.takumi.oneshot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCZiTuUaxrzhe3iWtT9zXGomvtGLLKn8c',
    appId: '1:22700401021:ios:457dccef61b65bda3cec14',
    messagingSenderId: '22700401021',
    projectId: 'oneshot-1107f',
    storageBucket: 'oneshot-1107f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlAeNXbtWYKAUCffIZzwlJI01JeUC0KGY',
    appId: '1:22700401021:web:33e6f5f5426922a43cec14',
    messagingSenderId: '22700401021',
    projectId: 'oneshot-1107f',
    authDomain: 'oneshot-1107f.firebaseapp.com',
    storageBucket: 'oneshot-1107f.firebasestorage.app',
  );
}
